# Generated by Django 3.0.7 on 2020-07-28 14:48

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0003_useradd_pic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Addblog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('post', models.TextField(max_length=2000)),
                ('date', models.DateTimeField(default=datetime.datetime(2020, 7, 28, 20, 18, 52, 917536))),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.UserAdd')),
            ],
        ),
    ]
