# Generated by Django 3.0.7 on 2020-07-24 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useradd',
            name='gender',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
