# Generated by Django 3.0.7 on 2020-07-27 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20200724_2000'),
    ]

    operations = [
        migrations.AddField(
            model_name='useradd',
            name='pic',
            field=models.ImageField(default='null', upload_to='static/images'),
            preserve_default=False,
        ),
    ]
